mlgruppe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('start.urls')),
    path('pit/', include('pit.urls')),
    path('wiki/', include('mywiki.urls')),
    path('postits/', include('postits.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('kurs/', include('kurse.urls')),
    path('trainer/', include('trainer.urls')),
    path('logistik/', include('logistik.urls')),
    path('kunden/', include('kunden.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mywiki/urls.py
from django.urls import path
from . import views
app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("new/", views.new_page, name="new_page"),
    path("edit/", views.edit, name="edit"),
    path("save_edit/", views.save_edit, name="save_edit"),
    path("rand/", views.rand, name="rand"),
    # path("signup/",views.SignUpView.as_view(), name="signup")
]

pit/urls.py
from django.urls import path, include
from . import views

app_name = "pit"

urlpatterns = [
    path('', views.schiene_chart, name='info'),
    path('update_status/<int:item_id>/', views.update_status, name='update_status'),
    path('create_abholung/', views.create_abholung, name='create_abholung'),
    path('create_versand/', views.create_versand, name='create_versand'),
    path('create_server/', views.create_server, name='create_server'),
    path('create_schiene/', views.create_schiene, name='create_schiene'),
    path('edit_schiene/<int:schiene_id>/', views.edit_schiene, name='edit_schiene'),
    path('edit_versand/<int:versand_id>/', views.edit_versand, name='edit_versand'),
    path('abholung_detail/<int:item_id>/', views.abholung_detail, name='abholung_detail'),
    path('update_status_zurueck/<int:item_id>/', views.update_status_zurueck, name='update_status_zurueck'),
    path('update_status_dpd/<int:versand_id>/', views.update_status_dpd, name='update_status_dpd'),
    path('update_status_standort/<int:item_id>/', views.update_status_standort, name='update_status_standort'),
    path('update_status_abholung/<int:item_id>/', views.update_status_abholung, name='update_status_abholung'),
    path('update_status_versand/<int:item_id>/', views.update_status_versand, name='update_status_versand'),
    path('set_versand_status/<int:versand_id>/', views.set_versand_status, name='set_versand_status'),
    path('set_rueckholung_status/<int:versand_id>/', views.set_rueckholung_status, name='set_rueckholung_status'),
]

start/urls.py
from django.urls import path
from . import views

app_name = "start"

urlpatterns = [
    path("", views.index, name="index"),
    path("logout/", views.logout_view, name="logout")


]

templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Seite bearbeiten</h1>
    <h2 class="alert alert-warning" role="alert">Keine ä,ö,ü,ß möglich. Bitte so ersetzen: ö=oe ä=ae ß=ss usw.</h2>
    <br/>
    {% if user.is_authenticated %}
    <form action="{% url 'wiki:save_edit' %}" method="POST">
        {% csrf_token %}
        <label>Titel:</label>
        <input type="text" name="title" value="{{ title }}">
        <br/>
        <label>Markdown Inhalt:</label>
        <br/>
        <textarea name="content" rows="2" cols="20">{{ content }}</textarea>
        <br/>
        <input type="submit" value="Edit" class="btn btn-primary">
    </form>
    {% else %}
          <div class="alert alert-danger" role="alert">
                <h2> Sie haben keine Zugrifsrechte für diese Seite oder Sie sind nicht Angemeldet</h2>
          </div>
    {% endif %}
{% endblock %}

templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{ title }}
{% endblock %}

{% block body %}
    {{ content | safe }}

    <form action="{% url 'wiki:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="entry_title" value="{{ title }}">
        <input type="submit" value="Edit" class="btn btn-danger">
    </form>
{% endblock %}

templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Fehler</h1>
    <p>{{ massage }}</p>
{% endblock %}

templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>Alle Seiten</h1>
    		
    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'wiki:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>



{% endblock %}

templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'wiki/bootstrap/css/bootstrap.min.css' %}">
        <link href="{% static 'wiki/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>MLGruppe-Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>


                <div>
                    <a href="{% url 'start:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:rand' %}">Zufällige Seite</a>
                </div>

		{% if user.is_authenticated%}
		<div>
                    <a href="{% url 'wiki:new_page' %}">Neue Seite erstellen</a>
                </div>

		<div>
                    <!-- <a href="#">Benutzer hinzufuegen</a> -->
                </div>
		{% endif %}

                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Neue Seite</h1>
    <h2 class="alert alert-warning" role="alert">Keine ä,ö,ü,ß möglich. Bitte so ersetzen: ö=oe ä=ae ß=ss usw.</h2>
    <br/>
    <form action="{% url 'wiki:new_page' %}" method="POST">
        {% csrf_token %}
        <label>Titel:</label>
        <input type="text" name="title" placeholder="Titel eingeben">
        <br/>
        <label>Markdown Inhalt:</label>
        <br/>
        <textarea name="content" rows="2" cols="20"></textarea>
        <br/>
        <input type="submit" value="Neue Seite" class="btn btn-primary">
    </form>

{% endblock %}

templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Search</h1>
{% if user.is_authenticated %}
    <ul>
        {% for entry in recommendation %}
            <li><a href="{% url 'wiki:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% else %}
      <div class="alert alert-danger" role="alert">
                <h2> Sie haben keine Zugrifsrechte für diese Seite oder Sie sind nicht Angemeldet</h2>
      </div>
{% endif %}
{% endblock %}

templates/encyclopedia/signup.html
{% extends 'encyclopedia/layout.html' %}

{% block title %} Benutzer Anlegen {% endblock %}

{% block body %}
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="SignUp">
    </form>

{% endblock %}