mlgruppe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('start.urls')),
    path('pit/', include('pit.urls')),
    path('wiki/', include('mywiki.urls')),
    path('postits/', include('postits.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('kurs/', include('kurse.urls')),
    path('trainer/', include('trainer.urls')),
    path('logistik/', include('logistik.urls')),
    path('kunden/', include('kunden.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pit/urls.py
from django.urls import path, include
from . import views

app_name = "pit"

urlpatterns = [
    path('', views.schiene_chart, name='info'),
    path('update_status/<int:item_id>/', views.update_status, name='update_status'),
    path('create_abholung/', views.create_abholung, name='create_abholung'),
    path('create_versand/', views.create_versand, name='create_versand'),
    path('create_server/', views.create_server, name='create_server'),
    path('create_schiene/', views.create_schiene, name='create_schiene'),
    path('edit_schiene/<int:schiene_id>/', views.edit_schiene, name='edit_schiene'),
    path('edit_versand/<int:versand_id>/', views.edit_versand, name='edit_versand'),
    path('abholung_detail/<int:item_id>/', views.abholung_detail, name='abholung_detail'),
    path('update_status_zurueck/<int:item_id>/', views.update_status_zurueck, name='update_status_zurueck'),
    path('update_status_dpd/<int:versand_id>/', views.update_status_dpd, name='update_status_dpd'),
    path('update_status_standort/<int:item_id>/', views.update_status_standort, name='update_status_standort'),
    path('update_status_abholung/<int:item_id>/', views.update_status_abholung, name='update_status_abholung'),
    path('update_status_versand/<int:item_id>/', views.update_status_versand, name='update_status_versand'),
    path('set_versand_status/<int:versand_id>/', views.set_versand_status, name='set_versand_status'),
    path('set_rueckholung_status/<int:versand_id>/', views.set_rueckholung_status, name='set_rueckholung_status'),
]

pit/forms.py
from django import forms
from .models import Abholung, Rueckholung, Versand, Schiene, Server


class AbholungForm(forms.ModelForm):
    class Meta:
        model = Abholung
        fields = '__all__'


class RueckholungForm(forms.ModelForm):
    class Meta:
        model = Rueckholung
        fields = '__all__'


class VersandForm(forms.ModelForm):

    class Meta:
        model = Versand
        fields = '__all__'


class SchieneForm(forms.ModelForm):
    class Meta:
        model = Schiene
        fields = '__all__'


class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        fields = '__all__'

PIT/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.shortcuts import render
from .models import Schiene, Server


def schiene_chart(request):
    # Zählen Sie die Anzahl der Schienen für jeden Status
    lager_count = Schiene.objects.filter(status='Lager').count()
    unterwegs_count = Schiene.objects.filter(status='Unterwegs').count()
    zurücksetzen_count = Schiene.objects.filter(status='Zurücksetzen').count()
    imagen_count = Schiene.objects.filter(status='Imagen').count()

    server_lager_count = Server.objects.filter(status='Lager').count()
    server_unterwegs_count = Server.objects.filter(status='Unterwegs').count()
    server_zurücksetzen_count = Server.objects.filter(status='Zurücksetzen').count()

    context = {
        'lager_count': lager_count,
        'unterwegs_count': unterwegs_count,
        'zurücksetzen_count': zurücksetzen_count,
        'imagen_count': imagen_count,
        'server_lager_count': server_lager_count,
        'server_unterwegs_count': server_unterwegs_count,
        'server_zurücksetzen_count': server_zurücksetzen_count
    }

    # Hole die Server und Schienen, die zurückgesetzt werden müssen
    items_to_reset = list(Schiene.objects.filter(status='Zurücksetzen')) + list(
        Server.objects.filter(status='Zurücksetzen'))

    context.update({
        'items_to_reset': items_to_reset
    })

    return render(request, 'pit/schiene_chart.html', context)


def update_status(request, item_id):
    try:
        item = Schiene.objects.get(pk=item_id)
    except Schiene.DoesNotExist:
        item = Server.objects.get(pk=item_id)

    item.status = 'Lager'
    item.save()

    return redirect('schiene_chart')

pit/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from .forms import AbholungForm, VersandForm, ServerForm, SchieneForm
from .models import Schiene, Server, Abholung, Versand, Rueckholung
from datetime import datetime, date, timedelta
from django.contrib.auth.decorators import user_passes_test


def is_pit_group(user):
    return user.groups.filter(name='pit').exists()


def schiene_chart(request):
    """
    Zähle die Anzahl der Schienen für jeden Status und Server

    ** Models **
    :model:`pit.Schiene`
    :model:`pit.Server`

    ** Template: **
    :template:`pit/schiene_chart.html`

    """
    # Schienen zählen basierend auf ihrem Status
    lager_count = Schiene.objects.filter(status='Lager').count()
    unterwegs_count = Schiene.objects.filter(status='Unterwegs').count()
    unterwegs = Schiene.objects.filter(status='Unterwegs')
    zurücksetzen_count = Schiene.objects.filter(status='Zurücksetzen').count()
    imagen_count = Schiene.objects.filter(status='Imagen').count()
    schienen_lager = Schiene.objects.filter(status='Lager')
    schiene_lager_versand_count = Schiene.objects.filter(status='Versand').count()
    schienen_lager_versand = Schiene.objects.filter(status='Versand')
    schienen_standort_count = Schiene.objects.filter(status='Standort').count()
    schienen_standort = Schiene.objects.filter(status='Standort')
    schienen_weiterleitung_count = Schiene.objects.filter(status='Weiterleitung').count()
    schienen_weiterleitung = Schiene.objects.filter(status='Weiterleitung')
    schienen_zurueck_count = Schiene.objects.filter(status='Rückholung').count()
    schienen_zurueck = Schiene.objects.filter(status='Rückholung')
    schienen_abholung = Schiene.objects.filter(status='Selbstabholung')

    # Server zählen basierend auf ihrem Status
    server_lager_count = Server.objects.filter(status='Lager').count()
    server_unterwegs_count = Server.objects.filter(status='Unterwegs').count()
    server_unterwegs = Server.objects.filter(status='Unterwegs')
    server_zurücksetzen_count = Server.objects.filter(status='Zurücksetzen').count()
    server_lager = Server.objects.filter(status='Lager')
    server_versand_count = Server.objects.filter(status='Versand').count()
    server_versand = Server.objects.filter(status='Versand')
    server_standort_count = Server.objects.filter(status='Standort').count()
    server_standort = Server.objects.filter(status='Standort')
    server_weiterleitung_count = Server.objects.filter(status='Weiterleitung').count()
    server_weiterleitung = Server.objects.filter(status='Weiterleitung')
    server_zurueck_count = Server.objects.filter(status='Rückholung').count()
    server_zurueck = Server.objects.filter(status='Rückholung')
    server_abholung = Server.objects.filter(status='Selbstabholung')

    # Sontiges
    abholung = Abholung.objects.all()
    versand_liste = Versand.objects.all().order_by('Datum' )
    rueckholung_liste = Rueckholung.objects.all().order_by('RueckDatum')
    # Sammle Elemente, die zurückgesetzt werden müssen
    items_to_reset = list(Schiene.objects.filter(status='Zurücksetzen')) + list(
        Server.objects.filter(status='Zurücksetzen'))

    '''
    Sammle Schienen, die zurückgeholt werden müssen wird erstmal nicht mehr gebraucht
    schienen_to_reset = SchieneBewegung.objects.exclude(schiene__status__in=['Lager', 'Zurücksetzen']).filter(
        rueckholung_datum__isnull=False).order_by('rueckholung_datum')
    current_week = datetime.now().isocalendar()[1]
    schienen_to_move = SchieneBewegung.objects.exclude(schiene__status__in=['Lager', 'Zurücksetzen']).filter(
        rueckholung_datum__week=current_week)
    '''
    # Aktualisiere Kontext für das Template
    context = {
        # Schienen
        'lager_count': lager_count,
        'unterwegs_count': unterwegs_count,
        'zurücksetzen_count': zurücksetzen_count,
        'imagen_count': imagen_count,
        'schiene_lager_versand_count': schiene_lager_versand_count,
        'schienen_lager_versand': schienen_lager_versand,
        'schienen_standort_count': schienen_standort_count,
        'schienen_standort': schienen_standort,
        'schienen_lager': schienen_lager,
        'unterwegs': unterwegs,
        'schienen_weiterleitung_count': schienen_weiterleitung_count,
        'schienen_weiterleitung': schienen_weiterleitung,
        'schienen_zurueck_count': schienen_zurueck_count,
        'schienen_zurueck_': schienen_zurueck,
        'schienen_abholung': schienen_abholung,

        # Server
        'server_lager': server_lager,
        'server_lager_count': server_lager_count,
        'server_unterwegs_count': server_unterwegs_count,
        'server_zurücksetzen_count': server_zurücksetzen_count,
        'server_versand_count': server_versand_count,
        'server_standort_count': server_standort_count,
        'server_versand': server_versand,
        'server_standort': server_standort,
        'server_unterwegs': server_unterwegs,
        'server_weiterleitung_count': server_weiterleitung_count,
        'server_weiterleitung': server_weiterleitung,
        'server_zurueck_count': server_zurueck_count,
        'server_zurueck': server_zurueck,
        'server_abholung': server_abholung,

        # sonstiges
        'items_to_reset': items_to_reset,
        'abholung': abholung,
        'versand_liste': versand_liste,
        'rueckholung_liste': rueckholung_liste,
    }

    return render(request, 'pit/schiene_chart.html', context)


@user_passes_test(is_pit_group)
def update_status(request, item_id):
    """
    Ändert den Status eines Elements auf "Lager"

    ** Views: **
    :views: ´schiene_char´

    ** Return: **
    :return: ´schiene_char´

    """
    try:
        item = Schiene.objects.get(pk=item_id)
    except ObjectDoesNotExist:
        try:
            item = Server.objects.get(pk=item_id)
        except ObjectDoesNotExist:
            return HttpResponse("Item not found", status=404)

    item.status = 'Lager'
    item.save()

    return redirect('pit:info')


@user_passes_test(is_pit_group)
def update_status_zurueck(request, item_id):
    """
    Ändert den Status eines Elements auf Zurücksetzen"

    ** Views: **
    :views: ´schiene_char´

    ** Return: **
    :return: ´schiene_char´

    """
    try:
        item = Schiene.objects.get(pk=item_id)
    except ObjectDoesNotExist:
        try:
            item = Server.objects.get(pk=item_id)
        except ObjectDoesNotExist:
            return HttpResponse("Item not found", status=404)

    item.status = 'Zurücksetzen'
    item.save()

    return redirect('pit:info')


@user_passes_test(is_pit_group)
def update_status_versand(request, item_id):
    """
    Ändert den Status eines Elements auf Unterwegs"

    ** Views: **
    :views: ´schiene_char´

    ** Return: **
    :return: ´schiene_char´

    """
    try:
        item = Schiene.objects.get(pk=item_id)
    except ObjectDoesNotExist:
        try:
            item = Server.objects.get(pk=item_id)
        except ObjectDoesNotExist:
            return HttpResponse("Item not found", status=404)

    item.status = 'Versand'
    item.save()

    return redirect('pit:info')


@user_passes_test(is_pit_group)
def update_status_standort(request, item_id):
    """
    Ändert den Status eines Elements auf Zurücksetzen"

    ** Views: **
    :views: ´schiene_char´

    ** Return: **
    :return: ´schiene_char´

    """
    try:
        item = Schiene.objects.get(pk=item_id)
    except ObjectDoesNotExist:
        try:
            item = Server.objects.get(pk=item_id)
        except ObjectDoesNotExist:
            return HttpResponse("Item not found", status=404)

    item.status = 'Standort'
    item.save()

    return redirect('pit:info')


@user_passes_test(is_pit_group)
def update_status_abholung(request, item_id):
    """
    Ändert den Status eines Elements auf Abholung"

    ** Views: **
    :views: ´schiene_char´

    ** Return: **
    :return: ´schiene_char´

    """
    try:
        item = Schiene.objects.get(id=item_id)
    except ObjectDoesNotExist:
        try:
            item = Server.objects.get(id=item_id)
        except ObjectDoesNotExist:
            return HttpResponse("Item not found", status=404)

    item.status = 'Selbstabholung'
    item.save()

    return redirect('pit:info')


@user_passes_test(is_pit_group)
def create_abholung(request):
    if request.method == 'POST':
        form = AbholungForm(request.POST)
        if form.is_valid():
            # Erstelle eine Abholungsinstanz, ohne sie zu speichern
            abholung = form.save(commit=False)
            abholung.status = 'Unterwegs'  # Setze den Statuswert
            abholung.save()  # Speichere die Instanz in der Datenbank
            return redirect('pit:info')  # Nach dem Speichern zum Kursliste-View weiterleiten
    else:
        form = AbholungForm()

    return render(request, 'pit/create_abholung.html', {'form': form})


def abholung_detail(request, item_id):
    abholung = get_object_or_404(Abholung, pk=item_id)
    return render(request, 'pit/abholung_detail.html', {'abholung': abholung})


@user_passes_test(is_pit_group)
def set_rueckholung_status(request, versand_id):
    if request.method == 'POST':
        rückholung = Versand.objects.get(id=versand_id)
        if rückholung.Schiene:
            rückholung.Schiene.status = 'Versand'
            rückholung.Schiene.save()
        if rückholung.Server:
            rückholung.Server.status = 'Versand'
            rückholung.Server.save()

        rückholung.delete()  # Löscht das Versand-Objekt aus der Datenbank
        return redirect('pit:info')  # Setzen Sie hier Ihr gewünschtes Redirect-Ziel


@user_passes_test(is_pit_group)
def update_status_dpd(request, versand_id):
    """
    Ändert den Status der zugehörigen Schiene und Server eines Versandobjekts auf 'Unterwegs'

    ** Views: **

templates/pit/abholung_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-3">
      <h1 class="text-center">Abholung Tour "Platzhalter für Strecken" </h1>
      <h4 class="text-center">Tour Datum: {{ abholung.Datum }}</h4>
       <hr>

    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Fahrer</h4>
                </div>
                <div class="card-body">

                      <p>Fahrer: {{ abholung.Vorname }} {{ abholung.Name }}</p>
                      <p>Fahrer2: {{ abholung.Vorname2 }} {{ abholung.Name2 }}</p>
                      <p>Mobil 1: {{ abholung.Mobile1 }}</p>
                      <p>Mobil 2: {{ abholung.Mobile2 }}</p>
                      <p>Email: {{ abholung.Email }}</p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Fahrzeug Informationen</h4>
                </div>
                <div class="card-body">
                     <p>Firmenwagen: {{ abholung.Firmenwagen }}</p>
                        {% if abholung.Firmenwagen == 'Mietfahrzeug' %}
                            <p>Fahrzeug Type: {{ abholung.Fahrzeug_Type }}</p>
                            <p>Kennzeichen: {{ abholung.Kennzeichen }}
                            <p>Verleiher: {{ abholung.Fahrzeugvermieter}} </p>
                         {% elif abholung.Firmenwagen == 'ja' %}
                            <p>Fahrzeug Type: {{ abholung.Fahrzeug_Type }}</p>
                            <p>Kennzeichen: {{ abholung.Kennzeichen }}
                         {% else %}
                            <p>Kennzeichen: {{ abholung.Kennzeichen }}
                        {% endif %}
                </div>
            </div>
        </div>
        <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Informationen Auftrag</h4>
                    </div>
                    <div class="card-body">
                        <p>VA: {{ abholung.VA_Nummer }}</p>
                        {% if abholung.Kunde == None %}
                            <p style="background-color: goldenrod">Kunde: Siehe Tourdaten </p>
                        {% else %}
                            <p>Kunde: {{ abholung.Kunde }}</p>
                            <p>Adresse: {{ abholung.Kunde.adresse }}</p>
                        {% endif %}
                        {% if not abholung.Schiene == None %}
                            <p>Schiene: {{ abholung.Schiene }} </p>
                        {% else %}
                            <p>Schiene: ohne Schiene</p>
                        {% endif %}
                        {% if not abholung.Server == None %}
                            <p>Server: ohne Server</p>
                        {% else %}
                            <p>Server: {{ abholung.Server }} </p>
                        {% endif %}
                        <p>Unternehmensteil: Platzhalter</p>
                    </div>
                </div>
        </div>
    </div>
    <div id="zuruecksetzen" class="mt-5 shadow">
        <div class="card-header text-center py-3" style="background-color: #999999">
            <h4 class="my-0 fw-normal">Tourdaten</h4>
        </div>
        <div class="card-body text-center">
            {{ abholung.Tourdaten | safe }}
        </div>
    </div>

     <!-- Button zum Aktualisieren des Schienenstatus auf Unterwegs -->
    {% if not abholung.Server == None %}
        <form method="post" action="{% url 'pit:update_status_abholung' abholung.Schiene.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Schiene Status auf Unterwegs setzen</button>
        </form>
    {% endif %}
    <!-- Button zum Aktualisieren des Serverstatus auf Unterwegs -->
    {% if not abholung.Schiene == None %}
        <form method="post" action="{% url 'pit:update_status_abholung' abholung.Schiene.id  %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Schienen Status auf Unterwegs setzen</button>
        </form>
    {% endif %}
    </div>
      <!-- Füge weitere Details hinzu, wie benötigt -->
</div>
{% endblock %}

templates/pit/create_abholung.html
{% extends 'base_dash.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-5 shadow">Neue Abholung erstellen</h1>
    <div class="mt-5 shadow">

        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}

            <!-- Hier fügst du ein verstecktes Input-Feld hinzu, um den Statuswert zu übermitteln -->


            <button type="submit" class="btn btn-primary">Abholung erstellen</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pit/create_schiene.html
{% extends 'base_dash.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-5 shadow">Schiene erstellen</h1>
    <div class="mt-5 shadow">

        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}

            <!-- Hier fügst du ein verstecktes Input-Feld hinzu, um den Statuswert zu übermitteln -->


            <button type="submit" class="btn btn-primary">Schiene speichern</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pit/create_server.html
{% extends 'base_dash.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-5 shadow">Server Hinzufügen</h1>
    <div class="mt-5 shadow">

        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}

            <!-- Hier fügst du ein verstecktes Input-Feld hinzu, um den Statuswert zu übermitteln -->


            <button type="submit" class="btn btn-primary">Server erstellen</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pit/create_versand.html
{% extends 'base_dash.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-5 shadow">Versand erstellen</h1>
    <div class="mt-5 shadow">

        <form method="post">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}

            <!-- Hier fügst du ein verstecktes Input-Feld hinzu, um den Statuswert zu übermitteln -->


            <button type="submit" class="btn btn-primary">Versand erstellen</button>
        </form>
    </div>
</div>

{% endblock %}

templates/pit/edit_Schiene.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Speichern</button>
</form>
{% endblock %}

templates/pit/edit_versand.html
{% extends 'base_dash.html' %}

{% block content %}
<div class="container mt-5">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Speichern</button>
    </form>
</div>
{% endblock %}

templates/pit/schienen_uebersicht.html
{% extends "base.html" %}

{% block title %}Schienen Übersicht{% endblock %}

{% block content %}
<nav class="navbar bg-body-tertiary">
  <form class="container-fluid justify-content-start">
    <a href="{% url 'pit:info' %}" class="btn btn-sm btn-outline-secondary" type="button">Übersicht</a>
    <a href="{% url 'pit:course_table' %}" class="btn btn-sm btn-outline-secondary" type="button">Schienenlogistik</a>
  </form>
</nav>

<div class="container mt-5">
    <div class="mt-5 shadow">
        <h1 class="text-center">Schienen Übersicht</h1>
        <table class="table">
            <thead>
                <tr>
                    <th>Schiene</th>
                    <th>Aktueller Status</th>
                    <th>Nächster Schritt</th>
                    <th>Nächstes Datum</th>
                    <th>DPD Beauftragt</th>
                    <th>Aktionen</th>
                </tr>
            </thead>
            <tbody>
                {% for schiene_info in schienen_infos %}
                <tr id="schiene_row_{{ schiene_info.schiene.id }}">
                    <td>{{ schiene_info.schiene }}</td>
                    <td>{{ schiene_info.aktueller_status }}</td>
                    <td>{{ schiene_info.naechster_schritt }}</td>
                    <td>{{ schiene_info.naechstes_datum }}</td>
                    <td>
                        <input type="checkbox" id="dpd_beauftragt_{{ schiene_info.schiene.id }}" {% if schiene_info.dpd_beauftragt %} checked {% endif %}>
                    </td>
                    <td>
                        <button type="button" class="btn btn-success" onclick="schieneZurueck({{ schiene_info.schiene.id }})" id="zurueck_{{ schiene_info.schiene.id }}">Zurück</button>
                        <button type="button" class="btn btn-warning" onclick="schieneWeiterleitenNeu({{ schiene_info.schiene.id }})" id="weiterleiten_{{ schiene_info.schiene.id }}">Weiterleiten</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script>
function schieneWeiterleitenNeu(schieneId) {
    const kundeId = document.getElementById("kunde").value;
    const weiterleitungsDatum = document.getElementById("weiterleitungsDatum").value;
    const rueckholungsDatum = document.getElementById("rueckholungDatum").value;

    fetch('/pfad/zur/schiene_weiterleiten_neu/', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRFToken': '{{ csrf_token }}'
        },
        body: JSON.stringify({
            schiene_id: schieneId,
            kunde_id: kundeId,
            weiterleitungs_datum: weiterleitungsDatum,
            rueckholungs_datum: rueckholungsDatum
        })
    })
    .then(response => response.json())
    .then(data => {
        if (data.status === 'success') {
            location.reload();
        } else {
            alert('Fehler: ' + data.message);
        }
    });
}
</script>
{% endblock %}