mlgruppe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('start.urls')),
    path('pit/', include('pit.urls')),
    path('wiki/', include('mywiki.urls')),
    path('postits/', include('postits.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('kurs/', include('kurse.urls')),
    path('trainer/', include('trainer.urls')),
    path('logistik/', include('logistik.urls')),
    path('kunden/', include('kunden.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

pit/urls.py
from django.urls import path, include
from . import views

app_name = "pit"

urlpatterns = [
    path('', views.schiene_chart, name='info'),
    path('update_status/<int:item_id>/', views.update_status, name='update_status'),
    path('create_abholung/', views.create_abholung, name='create_abholung'),
    path('create_versand/', views.create_versand, name='create_versand'),
    path('create_server/', views.create_server, name='create_server'),
    path('create_schiene/', views.create_schiene, name='create_schiene'),
    path('edit_schiene/<int:schiene_id>/', views.edit_schiene, name='edit_schiene'),
    path('edit_versand/<int:versand_id>/', views.edit_versand, name='edit_versand'),
    path('abholung_detail/<int:item_id>/', views.abholung_detail, name='abholung_detail'),
    path('update_status_zurueck/<int:item_id>/', views.update_status_zurueck, name='update_status_zurueck'),
    path('update_status_dpd/<int:versand_id>/', views.update_status_dpd, name='update_status_dpd'),
    path('update_status_standort/<int:item_id>/', views.update_status_standort, name='update_status_standort'),
    path('update_status_abholung/<int:item_id>/', views.update_status_abholung, name='update_status_abholung'),
    path('update_status_versand/<int:item_id>/', views.update_status_versand, name='update_status_versand'),
    path('set_versand_status/<int:versand_id>/', views.set_versand_status, name='set_versand_status'),
    path('set_rueckholung_status/<int:versand_id>/', views.set_rueckholung_status, name='set_rueckholung_status'),
]

postits/urls.py
from django.urls import path
from . import views


app_name = 'postits'

urlpatterns = [
    path('', views.postit_list, name='postit_list'),
    path('<int:id>/', views.postit_detail, name='postit_detail'),
    path('create/', views.postit_create, name='postit_create'),
    path('update/<int:postit_id>/', views.postit_update, name='postit_update'),
    path('delete/<int:postit_id>/', views.postit_delete, name='postit_delete'),
]

postits/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor.fields import RichTextField


class PostIt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = RichTextField()
    position_x = models.IntegerField(null=True, blank=True)
    position_y = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

postits/forms.py
from django import forms
from .models import PostIt


class PostItForm(forms.ModelForm):
    class Meta:
        model = PostIt
        fields = ['title', 'text']

postits/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import PostIt
from .forms import PostItForm


def postit_list(request):
    postits = PostIt.objects.all()
    return render(request, 'postits/postit_list.html', {'postits': postits})


def postit_detail(request, id):
    postit = PostIt.objects.get(id=id)
    return render(request, 'postits/postit_detail.html', {'postit': postit})


@login_required
def postit_create(request):
    if request.method == 'POST':
        form = PostItForm(request.POST)
        if form.is_valid():
            new_postit = form.save(commit=False)
            new_postit.user = request.user
            new_postit.save()
            return redirect('postits:postit_list')
    else:
        form = PostItForm()
    return render(request, 'postits/postit_form.html', {'form': form})


@login_required
def postit_update(request, postit_id):
    postit = get_object_or_404(PostIt, id=postit_id, user=request.user)

    if request.method == 'POST':
        form = PostItForm(request.POST, instance=postit)
        if form.is_valid():
            form.save()
            return redirect('postits:postit_list')
    else:
        form = PostItForm(instance=postit)

    return render(request, 'postits/postit_form.html', {'form': form})


@login_required
def postit_delete(request, postit_id):
    postit = get_object_or_404(PostIt, id=postit_id, user=request.user)
    postit.delete()
    return redirect('postits:postit_list')

templates/postits/postit_detail.html
{% extends 'base.html' %}

{% block title %}
  {{ postit.title }}
{% endblock %}

{% block content %}
  <h1>{{ postit.title }}</h1>
  <p>{{ postit.text|safe }}</p>
<a href="{% url 'postits:postit_update' postit.id %}" class="btn btn-primary">Bearbeiten</a>
{% endblock %}

templates/postits/postit_form.html
{% extends 'base.html' %}

{% block content %}
  <h1>Neues Post-It erstellen</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.media }}
    <div class="form-group">
        <label for="{{ form.title.id_for_label }}">Titel:</label>
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="{{ form.text.id_for_label }}">Text:</label>
        {{ form.text }}
    </div>
    <button type="submit" class="btn btn-primary">Speichern</button>
  </form>
{% endblock %}

templates/postits/postit_list.html
{% extends 'base.html' %}

{% block title %}
  Post-It Liste
{% endblock %}

{% block content %}
<div class="container shadow">

        <h1>Post-It Liste</h1>
        <a class="btn btn-primary" href="{% url 'postits:postit_create' %}">Neue Notiz</a>
    <p></p>
</div>
</br></br>
<div class="container">
    <div class="row">
        {% for postit in postits %}
            <div class="col-3">
                <div class="card" style="background-color: yellow;" draggable="true">
                    <div class="card-body">
                        <h5 class="card-title">{{ postit.title }} - {{ postit.created_at }}</h5>
                        <hr>
                        <p class="card-text">
                            {% if postit.text|safe|length > 100 %}
                                {{ postit.text|safe|slice:":100" }}... <a href="{% url 'postits:postit_detail' postit.id %}">(mehr)</a>
                            {% else %}
                                {{ postit.text }}
                            {% endif %}</p>
                        <a href="{% url 'postits:postit_update' postit.id %}" class="btn btn-primary">Bearbeiten</a>
                        <a href="{% url 'postits:postit_delete' postit.id %}" onclick="return confirm('Sind Sie sicher?');" class="btn btn-danger">Löschen</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}