kunden/urls.py
from django.urls import path, include
from . import views

app_name = "kunde"

urlpatterns = [

    path('create_kunde/', views.create_kunde, name='create_kunde'),

]

kurse/urls.py
from django.urls import path
from . import views

app_name = 'kurs'

urlpatterns = [
    # Andere URLs hier ...
    path('create/', views.create_kurs, name='create_kurs'),
    path('kurs_uebersicht/', views.kurs_uebersicht, name='kurs_uebersicht'),
    path('kurs_details/<int:va_nummer>/', views.kurs_details, name='kurs_details'),
    path('edit_kurs/<int:va_nummer>/', views.edit_kurs, name='edit_kurs'),
    # path('list/', views.kurs_list, name='kurs_list'),   Annahme, dass du auch eine kurs_list-View hast
]

mlgruppe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('start.urls')),
    path('pit/', include('pit.urls')),
    path('wiki/', include('mywiki.urls')),
    path('postits/', include('postits.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('kurs/', include('kurse.urls')),
    path('trainer/', include('trainer.urls')),
    path('logistik/', include('logistik.urls')),
    path('kunden/', include('kunden.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mywiki/urls.py
from django.urls import path
from . import views
app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("new/", views.new_page, name="new_page"),
    path("edit/", views.edit, name="edit"),
    path("save_edit/", views.save_edit, name="save_edit"),
    path("rand/", views.rand, name="rand"),
    # path("signup/",views.SignUpView.as_view(), name="signup")
]

pit/urls.py
from django.urls import path, include
from . import views

app_name = "pit"

urlpatterns = [
    path('', views.schiene_chart, name='info'),
    path('update_status/<int:item_id>/', views.update_status, name='update_status'),
    path('create_abholung/', views.create_abholung, name='create_abholung'),
    path('create_versand/', views.create_versand, name='create_versand'),
    path('create_server/', views.create_server, name='create_server'),
    path('create_schiene/', views.create_schiene, name='create_schiene'),
    path('edit_schiene/<int:schiene_id>/', views.edit_schiene, name='edit_schiene'),
    path('edit_versand/<int:versand_id>/', views.edit_versand, name='edit_versand'),
    path('abholung_detail/<int:item_id>/', views.abholung_detail, name='abholung_detail'),
    path('update_status_zurueck/<int:item_id>/', views.update_status_zurueck, name='update_status_zurueck'),
    path('update_status_dpd/<int:versand_id>/', views.update_status_dpd, name='update_status_dpd'),
    path('update_status_standort/<int:item_id>/', views.update_status_standort, name='update_status_standort'),
    path('update_status_abholung/<int:item_id>/', views.update_status_abholung, name='update_status_abholung'),
    path('update_status_versand/<int:item_id>/', views.update_status_versand, name='update_status_versand'),
    path('set_versand_status/<int:versand_id>/', views.set_versand_status, name='set_versand_status'),
    path('set_rueckholung_status/<int:versand_id>/', views.set_rueckholung_status, name='set_rueckholung_status'),
]

start/urls.py
from django.urls import path
from . import views

app_name = "start"

urlpatterns = [
    path("", views.index, name="index"),
    path("logout/", views.logout_view, name="logout")


]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
{% block head %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap 5.3 CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'boostrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'prism/css/prism.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}">
    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

<style>
    /* Stil für den Scroll-To-Top-Button */
    #scroll-to-top-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        display: none;
        z-index: 999;
    }

    #scroll-to-top-button {
        font-size: 24px;
    }


</style>



{% endblock %}
</head>

<body>
{% include 'navigation.html' %}
{% block content %}

{% endblock %}
<!-- Pfeil nach oben Link -->
<div id="scrollToTop" class="scroll-to-top">
  <i class="bi bi-arrow-up"></i>
</div>

<script src="{% static 'prism/js/prism.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>


{% include 'foot.html' %}

</body>

</html>

templates/foot.html
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Schiene Tortendiagramm
    var schieneCtx = document.getElementById('schieneChart').getContext('2d');
    var schieneData = {
        labels: ['Lager', 'Unterwegs', 'Zurücksetzen', 'Imagen',  'Am Standort', 'Abholung',],
        datasets: [{
            data: [
                {{ lager_count }},
                {{ unterwegs_count }},
                {{ zurücksetzen_count }},
                {{ imagen_count }},
                {{ schienen_standort_count }},
                {{ schiene_lager_versand_count }},

            ],
            backgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0','#4bc055', '#b66ecc' ],
            hoverBackgroundColor: ['#FF6384', '#36A2EB', '#FFCE56', '#4BC0C0','#4bc055', '#ac3ccf'  ]
        }]
    };
    var schienePieChart = new Chart(schieneCtx, {
        type: 'pie',
        data: schieneData,
        options: {
            responsive: true,
            maintainAspectRatio: false
        }
    });

    // Server Tortendiagramm
    var serverCtx = document.getElementById('serverChart').getContext('2d');
    var serverData = {
        labels: ['Lager', 'Unterwegs', 'Zurücksetzen', 'Am Standort', 'Versand'],
        datasets: [{
            data: [
                {{ server_lager_count }},
                {{ server_unterwegs_count }},
                {{ server_zurücksetzen_count }},
                {{ server_standort_count }},
                {{ server_versand_count }},
            ],
            backgroundColor: ['#FF9999', '#66B2FF', '#FFCC66','#4bc055', '#b66ecc'],
            hoverBackgroundColor: ['#FF6666', '#3399FF', '#FFB366','#4bc055', '#ac3ccf']
        }]
    };
    var serverPieChart = new Chart(serverCtx, {
        type: 'pie',
        data: serverData,
        options: {
            responsive: true,
            maintainAspectRatio: false
        }
    });
});
</script>
<!-- Hinzugefügtes JavaScript -->
<script>
  // JavaScript zum Scrollen nach oben
  const scrollToTopButton = document.getElementById("scrollToTop");

  window.addEventListener("scroll", () => {
    if (window.pageYOffset > 300) {
      scrollToTopButton.classList.add("show");
    } else {
      scrollToTopButton.classList.remove("show");
    }
  });

  scrollToTopButton.addEventListener("click", () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  });
</script>

<script>
    let currentSchieneId; // Speichert die aktuelle Schiene-ID

    function schieneZurueck(schieneId) {
        // AJAX-Anfrage zum Zurücksetzen der Schiene
        // ...
    }

    function schieneWeiterleiten(schieneId) {
        currentSchieneId = schieneId; // Speichern Sie die aktuelle Schiene-ID
        // Öffnen des Bootstrap-Modals
        let weiterleitungModal = new bootstrap.Modal(document.getElementById('weiterleitungModal'));
        weiterleitungModal.show();
    }

    // AJAX-Anfrage, wenn der Button im Modal gedrückt wird
    document.getElementById('submitWeiterleiten').addEventListener('click', function() {
        let kunde = document.getElementById('kunde').value;
        let weiterleitungsDatum = document.getElementById('weiterleitungsDatum').value;
        let rueckholungDatum = document.getElementById('rueckholungDatum').value;

        // Ihre AJAX-Anfrage hier, verwenden Sie currentSchieneId und die Formulardaten
        // ...
    });
</script>
<script>
  // Aktualisiertes JavaScript
  document.addEventListener("DOMContentLoaded", function() {
    // Referenzen zu den Elementen
    const dpdCheckbox = document.getElementById("dpd_beauftragt");
    const weiterleitenButton = document.getElementById("weiterleiten_button");
    const zurueckButton = document.getElementById("zurueck_button");

    // Event-Listener für das Checkbox-Element
    dpdCheckbox.addEventListener("change", function() {
      if(this.checked) {
        weiterleitenButton.removeAttribute("disabled");
        zurueckButton.removeAttribute("disabled");
      } else {
        weiterleitenButton.setAttribute("disabled", "disabled");
        zurueckButton.setAttribute("disabled", "disabled");
      }
    });
  });
</script>
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const draggables = document.querySelectorAll('.card');
        const containers = document.querySelectorAll('.col-3');

        draggables.forEach(draggable => {
            draggable.addEventListener('dragstart', () => {
                draggable.classList.add('dragging');
            });

            draggable.addEventListener('dragend', () => {
                draggable.classList.remove('dragging');
                // Code, um die neue Position in der Datenbank zu speichern
            });
        });

        containers.forEach(container => {
            container.addEventListener('dragover', (e) => {
                e.preventDefault();
                const dragging = document.querySelector('.dragging');
                container.appendChild(dragging);
            });
        });
    });
</script>
<script>
document.addEventListener('DOMContentLoaded', (event) => {
    $('#kursDetailsModal').on('show.bs.modal', function (event) {
        var button = event.relatedTarget;
        var vaNummer = button.getAttribute('data-va-nummer');
        // Hier können Sie AJAX verwenden, um Kursdetails basierend auf vaNummer zu laden und im Modal anzuzeigen
    })
});
</script>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/messages.html
<div class="container">
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                      {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
             </div>
            {% endfor %}
        {% endif %}

</div>

templates/nav_dash.html
<div class="sidebar border border-right col-md-3 col-lg-2 p-0 bg-body-tertiary">
      <div class="offcanvas-md offcanvas-end bg-body-tertiary" tabindex="-1" id="sidebarMenu" aria-labelledby="sidebarMenuLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="sidebarMenuLabel">Company name</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" data-bs-target="#sidebarMenu" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body d-md-flex flex-column p-0 pt-lg-3 overflow-y-auto">
          <ul class="nav flex-column">
              {% if request.user.groups.all.0.name == "pit" or request.user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'pit:info' %}">
                <svg class="bi"><use xlink:href="#house-fill"/></svg>
                PIT Home
              </a>
            </li>
             {%  endif %} 
          {% if request.user.groups.all.0.name == "orga" or request.user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2 active" aria-current="page" href="{% url 'kurs:kurs_uebersicht' %}">
                <svg class="bi"><use xlink:href="#house-fill"/></svg>
                Orga Home
              </a>
            </li>
             {%  endif %} 
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'pit:create_schiene' %}">
                <svg class="bi"><use xlink:href="#file-earmark"/></svg>
                Schiene hinzufügen
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'pit:create_server' %}">
                <svg class="bi"><use xlink:href="#file-earmark"/></svg>
                Server hinzufügen
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <svg class="bi"><use xlink:href="#cart"/></svg>
                Kurse
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'kunde:create_kunde' %}">
                <svg class="bi"><use xlink:href="#people"/></svg>
                Kunde Adressen
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'pit:create_versand' %}">
                <svg class="bi"><use xlink:href="#cart"/></svg>
                Versand
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="#">
                <svg class="bi"><use xlink:href="#cart"/></svg>
                Rückholung
              </a>
            </li>

          </ul>


          <hr class="my-3">

          <ul class="nav flex-column mb-auto">
          {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'admin:index' %}">
                <svg class="bi"><use xlink:href="#gear-wide-connected"/></svg>
                Admin Debug Dashboard
              </a>
            </li>
          {% endif %}
           <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'django-admindocs-docroot' %}">
                <svg class="bi"><use xlink:href="#file-earmark"/></svg>
                Zu den Admin-Dokumenten
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link d-flex align-items-center gap-2" href="{% url 'start:logout' %}">
                <svg class="bi"><use xlink:href="#door-closed"/></svg>
                Sign out
              </a>
            </li>
          </ul>
        </div>
      </div>

templates/navigation.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">PIT Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'start:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wiki:index' %}">Wiki</a>
        </li>
        {% if request.user.groups.all.0.name == "pit" or request.user.is_superuser %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'postits:postit_list' %}">Post-It</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pit:info' %}">PIT</a>
        </li>
        {% endif %}  
        {% if request.user.groups.all.0.name == "orga" or request.user.is_superuser %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Orga
          </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" aria-disabled="true" href="{% url 'kurs:kurs_uebersicht' %}">Kursübersicht</a></li>  
                <li><a class="dropdown-item" aria-disabled="true" href="{% url 'kurs:create_kurs' %}">Kurs erstellen</a></li>
                <li><a class="dropdown-item" aria-disabled="true" href="{% url 'trainer:create_trainer' %}">Trainer erstellen</a> </li>
            </ul>
        </li>
        {% endif %}      
      </ul>      
            {% comment %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            KI-TEST
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'textbot:home' %}">Text Erzeugung</a></li>
            <li><a class="dropdown-item" href="{% url 'codebot:suggest' %}">Code Erzeugung</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Allgemein</a></li>
          </ul>
        </li>
        {% endcomment %}
       

      
      <div class="d-flex" >
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="btn btn-warning" href="{% url 'dashboard:index' %}">Dashboard</a>
                  </li>
                  <li class="nav-item">
                    <a class="btn btn-danger" href="{% url 'start:logout' %}">LOGOUT</a>
                  </li>

              {% else %}
                  <li class="nav-item">
                    <a class="btn btn-success" href="{% url 'login' %}">LOGIN</a>
                  </li>
              {% endif %}
          </ul>
      </div>
    </div>
  </div>
</nav>